jobs:
- job: Build
  displayName: Build
  pool:
    name: MySelfHostedPool       # <-- your self-hosted agent pool
    demands:
      - agent.name -equals Agent # <-- optional, if you want a specific agent
  steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)
