trigger:
  branches:
    include:
      - test

stages:
- stage: BuildStage
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default 
      demands:
        - agent.name -equals Agent
    steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: registration-form-app
          dockerfile: $(Build.SourcesDirectory)/Dockerfile
          containerRegistry: dockerappregistry1
          tags: |
            $(Build.BuildId)

<<<<<<< HEAD
- job: DeployToAKS
  displayName: Deploy to AKS Test
  dependsOn: Build                
  pool:
    name: Default
    demands:
      - agent.name -equals Agent
  steps:
    - task: KubernetesManifest@1
      displayName: Deploy updated image to AKS test cluster
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: 'Azure-Connection-test-environment'
        azureResourceGroup: 'myapp-test-rg'
        kubernetesCluster: 'myapp-aks-test'
        manifests: 'k8s/test/*.yaml'
        containers: |
          dockerappregistry1.azurecr.io/registration-form-app:$(Build.BuildId)-test
        rolloutStatusTimeout: '300'   
=======
- stage: DeployStage
  displayName: Deploy Stage
  dependsOn: BuildStage
  jobs:
  - deployment: DeployToAKS
    displayName: Deploy to AKS Test
    environment: 'Test'
    pool:
      name: Default
      demands:
        - agent.name -equals Agent
    strategy:
      runOnce:
        deploy:
          steps:
            - task: KubernetesManifest@1
              displayName: Deploy prod cluster to AKS test resources
              inputs:
                action: 'deploy'
                connectionType: 'azureResourceManager'
                azureSubscriptionConnection: 'Azure-Connection-test-environment'
                azureResourceGroup: 'myapp-test-rg'
                kubernetesCluster: 'myapp-aks-test'
                manifests: 'k8s/test/*.yaml'
                containers: |
                  dockerappregistry1.azurecr.io/registration-form-app:$(Build.BuildId)
                rolloutStatusTimeout: '300'
>>>>>>> 7691c0d6adde57a6d7b84ceb274f2172b1471288
