trigger:
  branches:
    include:
      - test

jobs:
- job: Build
  displayName: Build and Push Image
  pool:
    name: Default
    demands:
      - agent.name -equals Agent
  steps:
    - task: Docker@2
      displayName: Build and push Docker image to ACR
      inputs:
        command: buildAndPush
        repository: registration-form-app
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
        containerRegistry: dockerappregistry1
        tags: |
          $(Build.BuildId)-test

- job: DeployToAKS
  displayName: Deploy to AKS Test
  dependsOn: Build                
  pool:
    name: Default
    demands:
      - agent.name -equals Agent
  steps:
    - task: KubernetesManifest@1
      displayName: Deploy updated image to AKS test cluster
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: 'Azure-Connection-test-environment'
        azureResourceGroup: 'myapp-test-rg'
        kubernetesCluster: 'myapp-aks-test'
        manifests: 'k8s/test/*.yaml'
        containers: |
          dockerappregistry1.azurecr.io/registration-form-app:$(Build.BuildId)-test
        rolloutStatusTimeout: '300'   
