version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=registrationdb;Username=appuser;Password=apppassword"

  postgres:
    image: postgres:15
    container_name: registration-postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: registrationdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
