apiVersion: v1
kind: Service
metadata:
  name: registration-form-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: registration-form-app
  ports:
    - port: 80
      targetPort: 8080
