apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: produser
  POSTGRES_PASSWORD: prodpassword
  POSTGRES_DB: proddb
  ConnectionStrings__DefaultConnection: "Host=postgres;Database=proddb;Username=produser;Password=prodpassword"
