apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: $(POSTGRES_PROD_USER)
  POSTGRES_PASSWORD: $(POSTGRES_PROD_PASSWORD)
  POSTGRES_DB: proddb
  ConnectionStrings__DefaultConnection: "Host=postgres;Database=proddb;Username=$(POSTGRES_PROD_USER);Password=(POSTGRES_PROD_PASSWORD)"
